FROM quay.io/buildah/stable:v1.11.0

LABEL maintainer "Devtools <devtools@redhat.com>"
LABEL author "Devtools <devtools@redhat.com>"

ENV USER_UID=1001 \
    USER_NAME=toolchain-cicd \
    LANG=en_US.utf8 \
    OPM_VERSION=v1.12.5

RUN curl -Lo opm https://github.com/operator-framework/operator-registry/releases/download/${OPM_VERSION}/linux-amd64-opm \
    && chmod +x opm \
    && cp opm /usr/bin/opm \
    && rm opm \
    && opm version