name: 'Checkout code from PR'
description: 'Checkout code from PR based either on PR event or comment event in that PR'
runs:
  using: "composite"
  steps:
  - name: Checkout code from PR event
    uses: actions/checkout@v2
    if: ${{ github.event.comment == '' }}
    with:
      ref: ${{github.event.pull_request.head.ref}}
      repository: ${{github.event.pull_request.head.repo.full_name}}
      fetch-depth: 0

  - name: Send Github API Request to get PR data
    id: request
    uses: octokit/request-action@v2.0.0
    if: ${{ github.event.pull_request == '' }}
    with:
      route: ${{ github.event.issue.pull_request.url }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  - name: Print out PR data
    id: pr_data
    run: |
      echo "::set-output name=json::${{ steps.request.outputs.data }}"

  - name: Checkout code from PR
    uses: actions/checkout@v2
    if: ${{ github.event.pull_request == '' }}
    with:
      repository: ${{ fromJson(steps.request.outputs.data).head.repo.full_name }}
      ref: ${{ fromJson(steps.request.outputs.data).head.ref }}
      fetch-depth: 0
