FROM golang:1.23 as builder

ARG GOOS
ARG GOARCH

WORKDIR /usr/src/app/  

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

RUN echo "Building for govulncheck $GOOS/$GOARCH"
RUN GOOS=$GOOS GOARCH=$GOARCH go build -v -o govulncheck main.go

FROM golang:1.23
# using a fresh golang image without the `WORKDIR` from the builder stage
# see https://docs.github.com/en/actions/reference/workflows-and-actions/dockerfile-support#workdir

# copy the binary from the builder stage
COPY --from=builder /usr/src/app/govulncheck /usr/local/bin/govulncheck

ENTRYPOINT ["/usr/local/bin/govulncheck"]