name: 'Prepare tools for Toolchain Operator release'
description: 'An action that installs tools like operator-sdk, podman, and opm'
inputs:
  operator-sdk-version:
    description: Version of operator-sdk binary
    required: false
    default: v1.16.0
  opm-version:
    description: Version of opm binary
    required: false
    default: v1.15.3
runs:
  using: "composite"
  steps:
  - name: Install Podman
    shell: bash
    run: |
      set -ex
      sudo apt-get update \
        && sudo apt-get -y install podman dbus-x11 \
        && podman version

  - name: Install operator-sdk, yq and opm
    shell: bash
    run: |
      set -ex

      # download, verify and install operator-sdk
      curl -L -s https://github.com/operator-framework/operator-sdk/releases/download/${{ inputs.operator-sdk-version }}/operator-sdk_linux_amd64 -o operator-sdk \
        && gpg --keyserver keyserver.ubuntu.com --recv-keys 052996E2A20B5C7E \
        && curl -L -s https://github.com/operator-framework/operator-sdk/releases/download/${{ inputs.operator-sdk-version }}/checksums.txt -o checksums.txt \
        && curl -L -s https://github.com/operator-framework/operator-sdk/releases/download/${{ inputs.operator-sdk-version }}/checksums.txt.asc -o checksums.txt.asc \
        && gpg -u "Operator SDK (release) <cncf-operator-sdk@cncf.io>" --verify checksums.txt.asc \
        && chmod +x operator-sdk \
        && sudo cp operator-sdk /bin/operator-sdk \
        && rm operator-sdk \
        && operator-sdk version

  - name: Install yq
    shell: bash
    run: |
      set -ex

      pip3 install yq

  - name: Install opm
    shell: bash
    run: |
      set -ex

      curl -Lo opm https://github.com/operator-framework/operator-registry/releases/download/${{ inputs.opm-version }}/linux-amd64-opm
      chmod +x opm \
        && sudo cp opm /bin/opm \
        && rm opm \
        && opm version


