---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-createwebhook
secrets:
- name: webhook-secret
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: create-or-update-webhook
spec:
  volumes:
  - name: github-secret
    secret:
      secretName: $(inputs.params.GitHubSecretName)
  inputs:
    params:
    - name: ExternalDomain
      description: "The external domain for the EventListener e.g. `$(inputs.params.EventListenerName).<PROXYIP>.nip.io`"
    - name: GitHubRepos
      description: "The GitHub repos where the webhook will be created"
    - name: GitHubOrg
      description: "The GitHub organization where the webhook will be created"
    - name: GitHubSecretName
      description: "The Secret name for GitHub access token. This is always mounted and must exist"
      default: "webhook-secret"
    - name: GitHubAccessTokenKey
      description: "The GitHub access token key name"
      default: "token"
    - name: GitHubSecretStringKey
      description: "The GitHub secret string key name"
      default: "secret"
    - name: GitHubDomain
      description: "The GitHub domain. Override for GitHub Enterprise"
      default: "github.com"
    - name: WebhookEvents
      description: "List of events the webhook will send notifications for"
      default: '[\"push\"]'
  steps:
  - name: create-webhook
    image: everpeace/curl-jq:latest
    volumeMounts:
    - name: github-secret
      mountPath: /var/secret
    script: |
      #!/bin/sh
      set -e
      for REPO in $(inputs.params.GitHubRepos); do
        echo "Create Webhook for ${REPO}"
        WEBHOOK_ID=`curl -v -H "Authorization: token $(cat /var/secret/$(inputs.params.GitHubAccessTokenKey))" -L https://api.github.com/repos/$(inputs.params.GitHubOrg)/${REPO}/hooks | jq '.[] | select(.config.url | contains ("$(inputs.params.ExternalDomain)")) | .id'`
        if [ -n "${WEBHOOK_ID}" ];then
          METHOD="PATCH"
          WEBHOOK_ID_SUFFIX="/${WEBHOOK_ID}"
        else
          METHOD="POST"
          WEBHOOK_ID_SUFFIX=""
        fi
        curl -v -d "{\"name\": \"web\",\"active\": true,\"events\": $(inputs.params.WebhookEvents),\"config\": {\"url\": \"$(inputs.params.ExternalDomain)\",\"content_type\": \"json\",\"insecure_ssl\": \"1\" ,\"secret\": \"$(cat /var/secret/$(inputs.params.GitHubSecretStringKey))\"}}" -X ${METHOD} -H "Authorization: token $(cat /var/secret/$(inputs.params.GitHubAccessTokenKey))" -L https://api.github.com/repos/$(inputs.params.GitHubOrg)/${REPO}/hooks${WEBHOOK_ID_SUFFIX}
      done
