apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: apply-webhooks
spec:
  params:
  - name: external-sync-domain
    description: The external domain for the sync EventListener
  - name: external-toolchain-cd-domain
    description: The external domain for the toolchain-cd EventListener
  - name: toolchain-cd-projects
    description: List of projects to be used for CD flow

  tasks:
  - name: apply-toolchain-cd-webhook
    taskRef:
      name: create-or-update-webhook
    params:
    - name: GitHubOrg
      value: "codeready-toolchain"
    - name: GitHubRepos
      value: "toolchain-cicd"
    - name: ExternalDomain
      value: $(params.external-sync-domain)
    - name: WebhookEvents
      value: '[\"push\",\"pull_request\"]'

  - name: apply-toolchain-cd-repo-webhook
    taskRef:
      name: create-or-update-webhook
    params:
    - name: GitHubOrg
      value: "codeready-toolchain"
    - name: GitHubRepos
      value: $(params.toolchain-cd-projects)
    - name: ExternalDomain
      value: $(params.external-toolchain-cd-domain)