= Scripts
This directory contains a set of bash scripts that helps us with maintaining and managing OLM catalog files. The following part describes the purpose and functionality of all the script files.

== olm-setup.sh
The `olm-setup.sh` script is a collection of common functions used by other scripts. Executing this script on its own wouldn't do anything.

== generate-cd-release-manifests.sh
The `generate-cd-release-manifests.sh` regenerates operator bundles manifests for the latest commit in master.
The simplified flow of the script is the following:

1. It calculates the version of the new CSV and of the previous one as well (if not already defined).
2. It runs the `make bundle` command inside of the operator repository in order to regenerate the operator bundle manifests.
3. It replaces the variables and parameters in the newly regenerated CSV.


== push-bundle-and-index-image.sh
The `push-bundle-and-index-image.sh` takes the current operator bundle manifests in the `deploy/olm-catalog/<operator-name>/` directory and using the files it generates bundle image (uses "staging" channel), adds it to an index image and pushes them to a repository in https://quay.io[].
The simplified flow of the script is the following:

1. Reads the new version in CSV and checks if it replaces an older version of the operator
2. Replaces the channel name to "staging" in both bundle.Dockerfile and metadata/annotations.yaml.
3. Builds a container for a bundle image.
4. Builds the bundle image and pushes it to quay.
5. Adds the bundle image to index image and pushes it to quay.
