= Scripts
This directory contains a set of bash scripts that helps us with maintaining and managing OLM catalog files. The following part describes the purpose and functionality of all the script files.

== enrich-by-envs-from-yaml.sh
The `enrich-by-envs-from-yaml.sh` script takes two parameters:

1. path to CSV the deployment variables should be added to
2. path to an environment configuration file

If the provided environment configuration file exists then it transforms it into a list of key-value pairs.
The keys are generated by joining all YAML keys that are on the path to the value.
For example, with the following environment configuration:
```yaml
registration-service:
  environment: 'dev'
  replicas: 2
  auth-client:
    library-url: 'https://sso..../keycloak.js'
    public-keys-url: 'https://sso..../certs'
```
the resulting list of key-value pairs would be:
``` yaml
REGISTRATION_SERVICE_ENV : 'dev'
REGISTRATION_SERVICE_REPLICAS : 2
REGISTRATION_SERVICE_AUTH_CLIENT_LIBRARY_URL : 'https://sso..../keycloak.js'
REGISTRATION_SERVICE_AUTH_CLIENT_PUBLIC_KEYS_URL : 'https://sso..../certs'
```
Once the key-value pairs have been generated, they are included in the CSV as additional environment parameters of the operator deployment.
The modified CSV is printed on the standard output.

== olm-setup.sh
The `olm-setup.sh` script is a collection of common functions used by other scripts. Executing this script on its own wouldn't do anything.

== generate-cd-release-manifests.sh
The `generate-cd-release-manifests.sh` regenerates operator bundles manifests for the latest commit in master.
The simplified flow of the script is the following:

1. It calculates the version of the new CSV and of the previous one as well (if not already defined).
2. It runs the `make bundle` command inside of the operator repository in order to regenerate the operator bundle manifests.
3. It replaces the variables and parameters in the newly regenerated CSV.
4. It executes the `enrich-by-envs-from-yaml.sh` script to parse the `<operator-repo>/deploy/env/prod.yaml` file (if it exists) and to add additional deployment variables into the CSV.


== push-bundle-and-index-image.sh
The `push-bundle-and-index-image.sh` takes the current operator bundle manifests in the `deploy/olm-catalog/<operator-name>/` directory and using the files it generates bundle image (uses "staging" channel), adds it to an index image and pushes them to a repository in https://quay.io[].
The simplified flow of the script is the following:

1. Reads the new version in CSV, parses it and checks if it contains 5 parts which means that when the CSV was being generated then either embedded or main repo was specified (eg. host-operator / registration-service)
2. If the version contains 5 parts then it checks if the "replaces" version corresponds to what is in the index image:
.. Reads the "replaces" version in the CSV
.. Calls `opm index export` command for the given index and operator name and redirects the output to a file
.. As soon as the file contains information that `opm` starts pulling bundle images, then the scripts stop the command and reads the latest version specified in the output line.
.. Compare the "replaces" version from CSV with the latest version in index and if
* they are the same, then it continues using the same "replaces" version.
* if they both have "at least something in common", then the script assumes that there was one or more commits of the same repository skipped so it uses the version from the index as the one for replacement.
* (there are more cases - see the script and the inline comments for more info)

3. Replaces the channel name to "staging" in both bundle.Dockerfile and metadata/annotations.yaml.
4. Builds a container for a bundle image.
5. Builds the bundle image and pushes it to quay.
6. Adds the bundle image to index image and pushes it to quay.
