apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: update-from-master-binding
spec:
  params:
  - name: gitref
    value: $(body.head_commit.id)
  - name: gitrepositoryurl
    value: $(body.repository.clone_url)