---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: toolchain-cd-sync-listener
spec:
  serviceAccountName: pipeline
  triggers:
  - name: toolchain-cd-sync-deploy-from-master
    interceptors:
    - cel:
        filter: header.match('X-GitHub-Event', 'push') && body.ref.startsWith('refs/heads/master')
    binding:
      name: update-from-master-binding
    template:
      name: update-from-master-template

  - name: toolchain-cicd-dry-run
    interceptors:
    - cel:
        filter: header.match('X-GitHub-Event', 'pull_request') && body.action == 'opened' || body.action == 'synchronize'
    binding:
      name: toolchain-cicd-dry-run-binding
    template:
      name: toolchain-cicd-dry-run-template
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: toolchain-cd-sync-eventlistener
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-toolchain-cd-sync-listener
    weight: 100