name: govulncheck-action
on:
  push:
    branches:
    - master
    tags-ignore:
    - '*.*'
    paths:
    - 'govulncheck-action/**'
    -  '.github/workflows/govulncheck-action.yml'
  pull_request:
    branches:
    - master
    paths:
    - 'govulncheck-action/**'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test govulncheck-action

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version-file: govulncheck-action/go.mod

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles ('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Test
      working-directory: govulncheck-action
      run: |
        make test

  lint:
    runs-on: ubuntu-latest
    name: Lint govulncheck-action
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Lint
      uses: golangci/golangci-lint-action@v8
      with:
        working-directory: govulncheck-action
        version: v2.1.6
        skip-pkg-cache: true
        skip-build-cache: true
        args: --config=.golangci.yml --verbose .